on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Run Pyinstaller
        run: |
          pyinstaller \
            --clean \
            --noconfirm \
            restim-macos.spec
          ls -lah dist/
          ls -lah dist/restim.app
          du -d2 dist/restim.app
      - name: tar files
        run: |
          cd dist && \
          tar -cvf restim.app.tar restim.app
      - name: adjust folders
        run: |
          mkdir dist/restim-mac-arm64
          mv dist/restim.app/ dist/restim-mac-arm64/
      - name: Upload Executable
        id: artifact_upload
        uses: eXhumer/upload-artifact@0b7d5f5684d3f642f978d2faad9ade64f5b4dd57
        with:
          name: restim-mac-arm64
          path: dist/restim-mac-arm64/
          follow-symlinks: false
