on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Run Pyinstaller
        run: |
          pyinstaller \
            --clean \
            --noconfirm \
            restim-macos.spec
          ls dist/
          cd dist/ &&
          zip -r9 restim restim.app/
      - name: chmod
        run: |
          ls dist
          ls dist/restim.app
          chmod u+x dist/restim
      - name: Upload Executable
        id: artifact_upload
        uses: actions/upload-artifact@v4
        with:
          name: restim.app
          path: dist/restim.app
          asset_content_type: application/zip
