on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          python_arch: 'x64'
          spec: 'restim.py'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'restim.exe'
          options: --onefile, --paths ".", --add-data "resources/phase diagram bg.svg;resources/", --add-data "resources/favicon.png;resources/", --icon resources/favicon.ico

          
